apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - tempo.yaml
  - otel-collector.yaml
  - grafana.yaml
  - prometheus.yaml
  - prometheus-rbac.yaml
  - kafka-exporter.yaml

configMapGenerator:
  - name: otel-collector-config
    files:
      - otel-collector-config.yaml
  - name: tempo-config
    files:
      - tempo-config.yaml
  - name: prometheus-config
    files:
      - prometheus-config.yaml

namespace: monitoring

generatorOptions:
  disableNameSuffixHash: true